remove static link for libgomp
1. use --path option to make compiled executile files will use
 patched libraries.
2. simpified imagemagick compiling script for further changes

diff --git a/apps/openmp/imagick/mk b/apps/openmp/imagick/mk
--- a/apps/openmp/imagick/mk
+++ b/apps/openmp/imagick/mk
@@ -2,39 +2,44 @@
 
 set -e
 
-if [ "$APPS_DIR" = "" ]; then
+if [ ! -d $XTERN_ROOT ]; then
+    echo "XTERN_ROOT is not defined"
+    exit 1
+fi
+
+if [ ! -d $APPS_DIR ]; then
 	echo '$APPS_DIR not defined, do `export APPS_DIR=`'
 	exit 1
 fi
 
 VER=6.8.0-4
-echo ""
-echo "Please make sure you have run the 'mk' in $XTERN_ROOT/apps/openmp before you build imagick."
-echo ""
-sleep 2
-cd $XTERN_ROOT/apps/openmp/imagick
-rm -rf ImageMagick-$VER install *.a
-tar zxvf $APPS_DIR/sys/ImageMagick-$VER.tar.gz
-ln -s $XTERN_ROOT/apps/openmp/install/lib64/libgomp.a
-ln -s $XTERN_ROOT/apps/openmp/install/lib64/libstdc++.a
-XTERN_ANNOT_LIB="-L$XTERN_ROOT/dync_hook -Wl,--rpath,$XTERN_ROOT/dync_hook -lxtern-annot"
 
-# compile ImageMagick
+echo -e "\nPlease make sure you have run the 'mk' in $XTERN_ROOT/apps/openmp before you build imagick.\n"
+sleep 1
+
+# cleanup
+cd $XTERN_ROOT/apps/openmp/imagick
+rm -rf ImageMagick-$VER install
+tar zxf $APPS_DIR/sys/ImageMagick-$VER.tar.gz
+
+# patch ImageMagick
 cd ImageMagick-$VER
 patch -p1 < ../add-convert-xtern-annot.patch
 patch -p1 < ../add-resize-xtern-annot.patch
 patch -p1 < ../add-compare-xtern-annot.patch
+
+# compile ImageMagick
 mkdir obj
 cd obj
+CC_HOME=$XTERN_ROOT/apps/openmp/install
 
-C_STATIC_LIB_GOMP="-g -O2 -static-libgcc -L$XTERN_ROOT/apps/openmp/imagick -fopenmp -lgomp"
-CXX_STATIC_LIB_GOMP=$C_STATIC_LIB_GOMP
-#"-static-libgcc -static-libstdc++ -D_GLIBCXX_PARALLEL -L$XTERN_ROOT/apps/openmp/imagick -fopenmp -lgomp"
-
-CFLAGS+="$C_STATIC_LIB_GOMP -I$XTERN_ROOT/include -L$XTERN_ROOT/dync_hook -Wl,--rpath,$XTERN_ROOT/dync_hook -lxtern-annot" \
-  CXXFLAGS+="$CXX_STATIC_LIB_GOMP -I$XTERN_ROOT/include -L$XTERN_ROOT/dync_hook -Wl,--rpath,$XTERN_ROOT/dync_hook -lxtern-annot" \
-  LIBS+="$CXX_STATIC_LIB_GOMP -L$XTERN_ROOT/dync_hook -Wl,--rpath,$XTERN_ROOT/dync_hook -lxtern-annot" \
-  ../configure --prefix=$XTERN_ROOT/apps/openmp/imagick/install --disable-shared --enable-static &> config.results
+CC="$CC_HOME/bin/gcc" \
+  CXX="$CC_HOME/bin/g++" \
+  CFLAGS+="-g -O2 -I$XTERN_ROOT/include -fopenmp" \
+  CXXFLAGS+="-g -O2 -I$XTERN_ROOT/include -fopenmp" \
+  LDFLAGS+="-L$CC_HOME/lib -Wl,--rpath,$CC_HOME/lib -L$CC_HOME/lib64 -Wl,--rpath,$CC_HOME/lib64 -L$XTERN_ROOT/dync_hook -Wl,--rpath,$XTERN_ROOT/dync_hook " \
+  LIBS+="-lgomp -lxtern-annot" \
+  ../configure --prefix=$XTERN_ROOT/apps/openmp/imagick/install --disable-shared --enable-static --enable-openmp 2>&1 | tee config.results
 
 make V=1 -j64
 make install
